#!/usr/bin/env python3
"""Expand contracts_corpus.json from 3 contracts to 9 (3 per difficulty)."""
import json, copy, pathlib

SRC = pathlib.Path("contracts_corpus.json")
DST = pathlib.Path("contract_risk_env/data/contracts_corpus.json")

corpus = json.loads(SRC.read_text())

# ── EASY 2: Cloud Storage Service Agreement ─────────────────────────────────
easy2 = {
    "contract_id": "cloud_storage_004",
    "difficulty": "easy",
    "title": "Cloud Storage Service Agreement",
    "parties": ["Provider: VaultStream Data Services Inc.", "Subscriber: Pinnacle Logistics Corp."],
    "notes": "Easy difficulty — all risks are explicitly titled and standalone.",
    "text": """CLOUD STORAGE SERVICE AGREEMENT

This Cloud Storage Service Agreement ("Agreement") is entered into as of the Effective Date by and between VaultStream Data Services Inc., a Nevada corporation ("Provider"), and the entity identified in the applicable Service Order ("Subscriber").

1. DEFINITIONS

1.1 "Storage Service" means Provider's cloud-based data storage, backup, and retrieval platform.

1.2 "Stored Data" means all files, databases, records, and content uploaded by Subscriber to the Storage Service.

1.3 "Service Period" means the initial term and any renewal periods specified in the Service Order.

2. SERVICE GRANT

2.1 Provider grants Subscriber a non-exclusive, non-transferable right to use the Storage Service during the Service Period for Subscriber's internal business purposes.

2.2 Subscriber shall not use the Storage Service to store unlawful content or content that infringes third-party intellectual property rights.

3. DATA HANDLING

3.1 Subscriber retains ownership of all Stored Data.

3.2 DATA LICENSE: Subscriber grants Provider an unrestricted, perpetual, irrevocable, worldwide, royalty-free license to access, copy, analyze, aggregate, de-identify, and commercially exploit Stored Data and any derivatives thereof for any purpose, including but not limited to training machine learning models, benchmarking, sale to third parties, and product development. Provider shall have no obligation to notify Subscriber of any such use.

3.3 Upon termination, Provider shall make Stored Data available for download for fifteen (15) days, after which Provider may delete all Stored Data without liability.

4. SERVICE TERM AND RENEWAL

4.1 The initial Service Period is specified in the Service Order.

4.2 AUTOMATIC RENEWAL: Unless Subscriber delivers written notice of cancellation by certified mail to Provider's registered office at least one hundred twenty (120) days before the end of the then-current Service Period, this Agreement shall automatically renew for successive two (2) year periods at Provider's then-current published rates, which may be increased without limitation. Subscriber acknowledges that email or phone notice shall not constitute valid cancellation.

5. FEES

5.1 UNILATERAL FEE ADJUSTMENT: Provider may adjust any fee, rate, surcharge, or pricing term under this Agreement at any time by posting updated pricing to Provider's website. Updated pricing shall take effect thirty (30) days after posting. Subscriber's continued use of the Storage Service after the effective date of any pricing change constitutes acceptance of the new pricing.

6. LIMITATION OF LIABILITY

6.1 IN NO EVENT SHALL PROVIDER BE LIABLE FOR ANY INDIRECT, INCIDENTAL, CONSEQUENTIAL, PUNITIVE, OR SPECIAL DAMAGES, OR FOR ANY DATA LOSS, WHETHER OR NOT PROVIDER HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.

6.2 PROVIDER'S TOTAL AGGREGATE LIABILITY SHALL NOT EXCEED THE FEES PAID BY SUBSCRIBER IN THE THREE (3) MONTHS PRECEDING THE CLAIM.

6.3 SUBSCRIBER LIABILITY: Notwithstanding any other provision of this Agreement, Subscriber's liability to Provider shall be unlimited and uncapped, including liability for direct, indirect, consequential, special, incidental, and punitive damages arising from Subscriber's breach of this Agreement, unauthorized use, or violation of applicable law.

7. TERMINATION BY PROVIDER

7.1 TERMINATION WITHOUT CAUSE: Provider may suspend or terminate Subscriber's access to the Storage Service at any time, for any reason or no reason, upon five (5) business days notice delivered through Provider's administrative portal. Provider shall have no obligation to refund prepaid fees upon such termination.

8. INTELLECTUAL PROPERTY

8.1 DERIVATIVE WORKS: All analytics, indices, metadata structures, search algorithms, and organizational frameworks generated by Provider's systems in connection with processing, organizing, or optimizing Stored Data ("Derived Works") shall be the sole and exclusive property of Provider. Subscriber irrevocably assigns to Provider all right, title, and interest in any Derived Works.

9. GOVERNING LAW

9.1 This Agreement shall be governed by the laws of the State of Nevada.""",
    "labels": [
        {
            "clause_id": "clause_3_2",
            "risk_type": "data_ownership_ambiguity",
            "severity": 3,
            "span_text": "Subscriber grants Provider an unrestricted, perpetual, irrevocable, worldwide, royalty-free license to access, copy, analyze, aggregate, de-identify, and commercially exploit Stored Data and any derivatives thereof for any purpose",
            "span_section": "Section 3.2",
            "grader_note": "Extremely broad data license despite 3.1 retaining nominal ownership. Provider can sell subscriber data."
        },
        {
            "clause_id": "clause_4_2",
            "risk_type": "auto_renewal",
            "severity": 2,
            "span_text": "Unless Subscriber delivers written notice of cancellation by certified mail to Provider's registered office at least one hundred twenty (120) days before the end of the then-current Service Period, this Agreement shall automatically renew for successive two (2) year periods",
            "span_section": "Section 4.2",
            "grader_note": "120-day certified mail notice, 2-year renewals at unlimited rate increases."
        },
        {
            "clause_id": "clause_5_1",
            "risk_type": "unilateral_amendment",
            "severity": 3,
            "span_text": "Provider may adjust any fee, rate, surcharge, or pricing term under this Agreement at any time by posting updated pricing to Provider's website.",
            "span_section": "Section 5.1",
            "grader_note": "Unilateral fee changes with only website posting. No consent needed."
        },
        {
            "clause_id": "clause_6_3",
            "risk_type": "unlimited_liability",
            "severity": 3,
            "span_text": "Subscriber's liability to Provider shall be unlimited and uncapped, including liability for direct, indirect, consequential, special, incidental, and punitive damages",
            "span_section": "Section 6.3",
            "grader_note": "Provider capped at 3 months fees, subscriber fully uncapped. Asymmetric."
        },
        {
            "clause_id": "clause_7_1",
            "risk_type": "termination_without_cause",
            "severity": 2,
            "span_text": "Provider may suspend or terminate Subscriber's access to the Storage Service at any time, for any reason or no reason, upon five (5) business days notice",
            "span_section": "Section 7.1",
            "grader_note": "5 days is extremely short for critical data storage. No refund."
        },
        {
            "clause_id": "clause_8_1",
            "risk_type": "ip_assignment_overreach",
            "severity": 2,
            "span_text": "All analytics, indices, metadata structures, search algorithms, and organizational frameworks generated by Provider's systems in connection with processing, organizing, or optimizing Stored Data (\"Derived Works\") shall be the sole and exclusive property of Provider.",
            "span_section": "Section 8.1",
            "grader_note": "Provider owns all derived analytical work product from subscriber's data."
        }
    ]
}

# ── EASY 3: API Platform Terms of Service ────────────────────────────────────
easy3 = {
    "contract_id": "api_platform_005",
    "difficulty": "easy",
    "title": "API Platform Terms of Service",
    "parties": ["Platform: DataBridge API Corp.", "Developer: NovaTech Solutions LLC"],
    "notes": "Easy difficulty — risks clearly labeled in section headings.",
    "text": """API PLATFORM TERMS OF SERVICE

These Terms of Service ("Terms") govern Developer's use of the DataBridge API Platform ("Platform") provided by DataBridge API Corp. ("DataBridge"). By accessing the Platform, Developer agrees to these Terms.

1. PLATFORM ACCESS

1.1 DataBridge grants Developer a revocable, non-exclusive, non-transferable license to access and use the Platform APIs for Developer's applications.

1.2 Developer shall comply with all rate limits, usage policies, and technical documentation.

2. DEVELOPER APPLICATIONS

2.1 Developer retains ownership of applications built using the Platform APIs.

2.2 IP ASSIGNMENT: Developer hereby assigns to DataBridge all right, title, and interest in any plugin, extension, connector, wrapper, middleware, or integration layer that interfaces with, connects to, or extends the Platform APIs ("Platform Integrations"). Developer irrevocably waives all moral rights in Platform Integrations. DataBridge grants Developer a revocable, non-exclusive license to use Platform Integrations solely during the term of these Terms.

3. SUBSCRIPTION AND RENEWAL

3.1 Developer selects a pricing tier during registration.

3.2 AUTO-RENEWAL: Each subscription period shall automatically renew for successive periods of equal length at DataBridge's then-current pricing unless Developer cancels through the Platform dashboard at least sixty (60) days prior to renewal. DataBridge reserves the right to modify pricing tiers, feature sets, and rate limits between renewal periods without prior notice.

4. MODIFICATIONS TO TERMS

4.1 UNILATERAL AMENDMENT: DataBridge may modify these Terms at any time by posting revised Terms to the Platform. Continued use of the Platform after posting constitutes Developer's irrevocable acceptance of all modifications. DataBridge has no obligation to notify Developer of changes. Developer is responsible for reviewing these Terms periodically.

5. INDEMNIFICATION

5.1 Developer shall indemnify and hold harmless DataBridge from any claims arising from Developer's applications, data processing, end-user complaints, regulatory actions, or breach of these Terms. This indemnification obligation is unlimited and not subject to any liability cap.

5.2 DataBridge shall indemnify Developer solely against third-party IP infringement claims related to the core Platform APIs as delivered.

6. LIABILITY

6.1 DATABRIDGE'S TOTAL LIABILITY SHALL NOT EXCEED THE FEES PAID BY DEVELOPER IN THE PRECEDING THIRTY (30) DAYS.

6.2 Developer's liability to DataBridge under these Terms shall be unlimited.

7. DATA USAGE

7.1 DataBridge may collect, analyze, and commercially use all API call data, request payloads, response patterns, and usage telemetry ("Platform Data") without restriction. Developer grants DataBridge an irrevocable license to use Platform Data for any purpose including sale to third parties.

8. TERMINATION

8.1 TERMINATION WITHOUT CAUSE: DataBridge may terminate Developer's access immediately without notice for any reason. Upon termination, all licenses granted to Developer are immediately revoked.

9. GOVERNING LAW

9.1 These Terms shall be governed by the laws of the State of California.""",
    "labels": [
        {
            "clause_id": "clause_2_2",
            "risk_type": "ip_assignment_overreach",
            "severity": 3,
            "span_text": "Developer hereby assigns to DataBridge all right, title, and interest in any plugin, extension, connector, wrapper, middleware, or integration layer that interfaces with, connects to, or extends the Platform APIs",
            "span_section": "Section 2.2",
            "grader_note": "Any integration work built by developer is assigned to DataBridge."
        },
        {
            "clause_id": "clause_3_2",
            "risk_type": "auto_renewal",
            "severity": 2,
            "span_text": "Each subscription period shall automatically renew for successive periods of equal length at DataBridge's then-current pricing unless Developer cancels through the Platform dashboard at least sixty (60) days prior to renewal.",
            "span_section": "Section 3.2",
            "grader_note": "60-day notice window. Pricing and features can change without notice between renewals."
        },
        {
            "clause_id": "clause_4_1",
            "risk_type": "unilateral_amendment",
            "severity": 3,
            "span_text": "DataBridge may modify these Terms at any time by posting revised Terms to the Platform. Continued use of the Platform after posting constitutes Developer's irrevocable acceptance of all modifications.",
            "span_section": "Section 4.1",
            "grader_note": "No notice, no consent, immediate effect."
        },
        {
            "clause_id": "clause_5_1",
            "risk_type": "indemnification_asymmetry",
            "severity": 2,
            "span_text": "Developer shall indemnify and hold harmless DataBridge from any claims arising from Developer's applications, data processing, end-user complaints, regulatory actions, or breach of these Terms. This indemnification obligation is unlimited",
            "span_section": "Section 5.1",
            "grader_note": "Developer's indemnity is unlimited and covers everything. DataBridge's indemnity (5.2) is narrow."
        },
        {
            "clause_id": "clause_6_2",
            "risk_type": "unlimited_liability",
            "severity": 3,
            "span_text": "Developer's liability to DataBridge under these Terms shall be unlimited.",
            "span_section": "Section 6.2",
            "grader_note": "DataBridge capped at 30 days fees. Developer unlimited."
        },
        {
            "clause_id": "clause_7_1",
            "risk_type": "data_ownership_ambiguity",
            "severity": 2,
            "span_text": "DataBridge may collect, analyze, and commercially use all API call data, request payloads, response patterns, and usage telemetry (\"Platform Data\") without restriction.",
            "span_section": "Section 7.1",
            "grader_note": "Request payloads may contain sensitive data. Broad commercial use rights."
        },
        {
            "clause_id": "clause_8_1",
            "risk_type": "termination_without_cause",
            "severity": 3,
            "span_text": "DataBridge may terminate Developer's access immediately without notice for any reason.",
            "span_section": "Section 8.1",
            "grader_note": "Immediate termination, no notice period at all."
        }
    ]
}

# ── MEDIUM 2: Data Processing Agreement ──────────────────────────────────────
medium2 = {
    "contract_id": "data_proc_006",
    "difficulty": "medium",
    "title": "Data Processing and Analytics Services Agreement",
    "parties": ["Processor: Quantis Data Analytics Ltd.", "Controller: Meridian Healthcare Group"],
    "notes": "Medium — risks require connecting definitions to operative clauses. The indemnity trap requires reading Schedules references. IP overreach is hidden in 'quality assurance' language.",
    "text": """DATA PROCESSING AND ANALYTICS SERVICES AGREEMENT

This Data Processing and Analytics Services Agreement ("Agreement") is made by and between Quantis Data Analytics Ltd., a UK company ("Processor"), and Meridian Healthcare Group, a Delaware corporation ("Controller").

1. DEFINITIONS

1.1 "Controller Data" means personal data and business records provided by Controller to Processor for processing.

1.2 "Analytical Outputs" means any report, model, insight, benchmark, score, prediction, classification, cluster analysis, or statistical derivative produced by Processor through the application of its proprietary algorithms and methodologies to any data, including Controller Data, whether processed in isolation or in combination with data from other sources.

1.3 "Processing Fee Period" means each consecutive twelve-month period beginning on the Effective Date. At the conclusion of each Processing Fee Period, a new Processing Fee Period shall commence automatically under the Continuous Service Commitment described in Section 4.3.

1.4 "Material Processing Change" means any modification to Processor's algorithms, infrastructure, data handling procedures, subprocessor relationships, or pricing that Processor determines, in its sole discretion, is material.

2. SERVICES

2.1 Processor shall process Controller Data in accordance with Controller's documented instructions and applicable data protection legislation.

2.2 Processor shall implement appropriate technical and organizational measures to protect Controller Data.

2.3 Quality Assurance Program. To ensure the highest quality of analytical services, Processor shall continuously monitor, evaluate, and refine its algorithms and models. As part of this quality assurance program, Processor shall retain copies of Controller Data and all intermediate processing states for the purpose of algorithm validation, model training, performance benchmarking, and service improvement. Controller acknowledges that Processor's quality assurance activities are essential to service delivery and consents to such retention and use.

3. INTELLECTUAL PROPERTY

3.1 Controller retains all rights in Controller Data.

3.2 Analytical Outputs. All Analytical Outputs, as defined in Section 1.2, regardless of whether they are generated primarily from Controller Data or incorporate Controller-specific configurations, parameters, or domain knowledge contributed by Controller personnel, shall be the exclusive property of Processor. Controller hereby assigns to Processor any interest Controller may have in Analytical Outputs. For clarity, the broad definition of Analytical Outputs in Section 1.2 encompasses any work product that results from processing activities, including custom reports commissioned and paid for by Controller.

4. TERM

4.1 This Agreement commences on the Effective Date and continues for an initial period of twenty-four (24) months.

4.2 Either party may terminate for material breach upon ninety (90) days written notice if the breach remains uncured.

4.3 Continuous Service Commitment. To ensure uninterrupted data processing capabilities and to protect Controller's operational continuity, upon expiration of the initial period and each subsequent Processing Fee Period as defined in Section 1.3, this Agreement shall continue automatically. Controller may elect to conclude the Agreement by submitting a formal termination request through Processor's client governance portal, which must be approved by Processor's client retention committee. Processor shall respond to termination requests within sixty (60) business days. Fees during any continuation period shall be subject to Processor's then-current rate card, as adjusted pursuant to Material Processing Changes under Section 1.4.

5. INDEMNIFICATION

5.1 Processor shall indemnify Controller against third-party claims that Processor's platform infringes valid intellectual property rights, subject to the limitations in Schedule E (which caps Processor's indemnity at one month of processing fees).

5.2 Controller shall indemnify Processor against all claims, liabilities, and expenses arising from or related to Controller Data, Controller's use of Analytical Outputs, Controller's failure to obtain required data subject consents, regulatory fines imposed on Processor in connection with Controller Data, and any downstream use of Analytical Outputs by Controller's patients, partners, or affiliates. Controller's indemnification obligations under this Section are not subject to any cap or limitation, notwithstanding any general limitation of liability in this Agreement or any Schedule.

6. LIABILITY

6.1 Processor's aggregate liability shall not exceed the processing fees paid by Controller in the six (6) months immediately preceding the claim.

6.2 Neither party shall be liable for indirect or consequential damages.

7. DATA RETENTION

7.1 Upon termination, Processor shall return or delete Controller Data within ninety (90) days, subject to Processor's right to retain data required for the quality assurance program described in Section 2.3 and for compliance with legal obligations. Processor may retain anonymized and aggregated versions of Controller Data indefinitely.

8. GOVERNING LAW

8.1 This Agreement shall be governed by the laws of England and Wales.""",
    "labels": [
        {
            "clause_id": "clause_1_2",
            "risk_type": "ip_assignment_overreach",
            "severity": 3,
            "span_text": "\"Analytical Outputs\" means any report, model, insight, benchmark, score, prediction, classification, cluster analysis, or statistical derivative produced by Processor through the application of its proprietary algorithms and methodologies to any data, including Controller Data",
            "span_section": "Section 1.2 (definition applied in Section 3.2)",
            "grader_note": "The definition is so broad that custom paid-for reports are captured. Must cross-reference Section 3.2 to see the full trap."
        },
        {
            "clause_id": "clause_2_3",
            "risk_type": "data_ownership_ambiguity",
            "severity": 2,
            "span_text": "Processor shall retain copies of Controller Data and all intermediate processing states for the purpose of algorithm validation, model training, performance benchmarking, and service improvement.",
            "span_section": "Section 2.3",
            "grader_note": "Hidden under 'Quality Assurance'. Healthcare data retained indefinitely for training. See also Section 7.1."
        },
        {
            "clause_id": "clause_4_3",
            "risk_type": "auto_renewal",
            "severity": 3,
            "span_text": "upon expiration of the initial period and each subsequent Processing Fee Period as defined in Section 1.3, this Agreement shall continue automatically. Controller may elect to conclude the Agreement by submitting a formal termination request through Processor's client governance portal, which must be approved by Processor's client retention committee.",
            "span_section": "Section 4.3 (requires reading Section 1.3)",
            "grader_note": "Auto-continuation hidden under 'Continuous Service Commitment'. Exit requires portal submission AND committee approval within 60 business days."
        },
        {
            "clause_id": "clause_5_2",
            "risk_type": "indemnification_asymmetry",
            "severity": 3,
            "span_text": "Controller shall indemnify Processor against all claims, liabilities, and expenses arising from or related to Controller Data, Controller's use of Analytical Outputs, Controller's failure to obtain required data subject consents, regulatory fines imposed on Processor in connection with Controller Data",
            "span_section": "Section 5.2",
            "grader_note": "Controller indemnity is unlimited (explicit override of liability caps). Processor indemnity capped at 1 month fees per Schedule E. Massive asymmetry."
        }
    ]
}

# ── MEDIUM 3: Technology Partnership Agreement ──────────────────────────────
medium3 = {
    "contract_id": "tech_partner_007",
    "difficulty": "medium",
    "title": "Strategic Technology Partnership Agreement",
    "parties": ["Platform Partner: Synapse AI Systems Corp.", "Integration Partner: Coastal Robotics Inc."],
    "notes": "Medium — risks buried in reciprocal-looking clauses. The 'mutual' IP sharing has asymmetric commercialization rights. Termination is technically mutual but has asymmetric consequences.",
    "text": """STRATEGIC TECHNOLOGY PARTNERSHIP AGREEMENT

This Strategic Technology Partnership Agreement ("Agreement") is entered into by and between Synapse AI Systems Corp. ("Platform Partner") and Coastal Robotics Inc. ("Integration Partner").

1. DEFINITIONS

1.1 "Integration Work" means any software, firmware, driver, adapter, protocol handler, or configuration developed by Integration Partner to enable interoperability between Integration Partner's products and Platform Partner's systems.

1.2 "Joint Development Output" means any technology, methodology, algorithm, or process arising from collaborative activities under this Agreement, whether contributed predominantly by one party or jointly.

1.3 "Applicable Renewal Fee" means, for each Renewal Term, the greater of (a) one hundred twenty-five percent (125%) of the fee applicable to the immediately preceding term, or (b) Platform Partner's then-current standard partnership fee for Integration Partner's usage tier.

2. PARTNERSHIP SCOPE

2.1 The parties shall collaborate on technology integration projects as described in project plans agreed from time to time.

2.2 Each party shall designate a partnership manager to coordinate activities.

3. INTELLECTUAL PROPERTY

3.1 Background IP. Each party retains all rights in its pre-existing intellectual property.

3.2 Integration Work. All Integration Work, regardless of whether it was developed solely by Integration Partner using Integration Partner's resources, shall be jointly owned by the parties. However, Platform Partner shall have the exclusive right to distribute, sublicense, and commercialize all Integration Work through Platform Partner's marketplace, partner ecosystem, and any other channel, without compensation to Integration Partner beyond the partnership benefits described in this Agreement.

3.3 Joint Development Output. All Joint Development Output shall be owned exclusively by Platform Partner. Integration Partner hereby assigns all right, title, and interest in Joint Development Output to Platform Partner and shall execute such documents as Platform Partner may request to perfect such assignment.

4. TERM AND RENEWAL

4.1 The initial partnership term is three (3) years from the Effective Date.

4.2 Renewal. Upon expiration of the initial term or any Renewal Term, this Agreement shall automatically renew for consecutive two (2) year Renewal Terms at the Applicable Renewal Fee defined in Section 1.3, unless a party provides written notice of non-renewal at least one hundred eighty (180) days before expiration. For the avoidance of doubt, the 180-day notice period runs from the date of receipt of notice by the other party, not the date of sending.

5. TERMINATION CONSEQUENCES

5.1 Upon termination or expiration, Integration Partner's license to use Platform Partner's APIs and systems shall immediately cease.

5.2 Integration Partner shall cease all distribution of Integration Work within thirty (30) days of termination and shall transfer to Platform Partner all source code, documentation, and deployment materials for Integration Work.

5.3 Platform Partner's rights to Integration Work and Joint Development Output survive termination and are perpetual.

6. INDEMNIFICATION

6.1 Integration Partner shall indemnify Platform Partner against all claims arising from Integration Work, Integration Partner's products, or Integration Partner's breach of this Agreement.

6.2 Platform Partner shall indemnify Integration Partner against third-party claims that Platform Partner's core platform infringes valid US patents, limited to the fees paid by Integration Partner in the twelve (12) months preceding the claim.

7. LIABILITY

7.1 NEITHER PARTY'S LIABILITY SHALL EXCEED THE TOTAL FEES PAID OR PAYABLE UNDER THIS AGREEMENT IN THE TWELVE MONTHS PRECEDING THE CLAIM, EXCEPT THAT INTEGRATION PARTNER'S LIABILITY FOR BREACHES OF SECTIONS 3 AND 5 SHALL BE UNLIMITED.

8. GOVERNING LAW

8.1 This Agreement shall be governed by the laws of the State of Massachusetts.""",
    "labels": [
        {
            "clause_id": "clause_3_2",
            "risk_type": "ip_assignment_overreach",
            "severity": 3,
            "span_text": "All Integration Work, regardless of whether it was developed solely by Integration Partner using Integration Partner's resources, shall be jointly owned by the parties. However, Platform Partner shall have the exclusive right to distribute, sublicense, and commercialize all Integration Work",
            "span_section": "Section 3.2",
            "grader_note": "'Jointly owned' but Platform Partner gets exclusive commercialization. Joint ownership is economically worthless for Integration Partner."
        },
        {
            "clause_id": "clause_3_3",
            "risk_type": "ip_assignment_overreach",
            "severity": 3,
            "span_text": "All Joint Development Output shall be owned exclusively by Platform Partner. Integration Partner hereby assigns all right, title, and interest in Joint Development Output to Platform Partner",
            "span_section": "Section 3.3",
            "grader_note": "Full assignment of collaborative work product. Combined with broad Section 1.2 definition, captures everything."
        },
        {
            "clause_id": "clause_4_2",
            "risk_type": "auto_renewal",
            "severity": 2,
            "span_text": "this Agreement shall automatically renew for consecutive two (2) year Renewal Terms at the Applicable Renewal Fee defined in Section 1.3, unless a party provides written notice of non-renewal at least one hundred eighty (180) days before expiration",
            "span_section": "Section 4.2 (requires reading Section 1.3)",
            "grader_note": "180-day notice. Fee is 125% of prior or current list price, whichever is higher. Must cross-reference Section 1.3."
        },
        {
            "clause_id": "clause_7_1",
            "risk_type": "unlimited_liability",
            "severity": 2,
            "span_text": "INTEGRATION PARTNER'S LIABILITY FOR BREACHES OF SECTIONS 3 AND 5 SHALL BE UNLIMITED",
            "span_section": "Section 7.1",
            "grader_note": "Appears mutual but exception applies only to Integration Partner. IP and termination breaches are uncapped."
        }
    ]
}

# ── HARD 2: Joint Venture Technology Services Agreement ──────────────────────
hard2 = {
    "contract_id": "jv_tech_008",
    "difficulty": "hard",
    "title": "Joint Venture — Technology Services Agreement",
    "parties": ["Lead Partner: Apex Digital Infrastructure Inc.", "Venture Partner: TerraNova Energy Solutions Ltd."],
    "notes": "Hard — risks hidden inside protective language. 'Knowledge sharing' clause is actually a data extraction mechanism. 'Balanced governance' has a casting vote that removes balance. Equal exit rights have asymmetric financial consequences.",
    "text": """JOINT VENTURE — TECHNOLOGY SERVICES AGREEMENT

This Joint Venture Technology Services Agreement ("Agreement") is made by and between Apex Digital Infrastructure Inc. ("Lead Partner") and TerraNova Energy Solutions Ltd. ("Venture Partner"), collectively the "JV Parties."

1. DEFINITIONS

1.1 "JV Entity" means the joint venture entity to be formed by the JV Parties for the purposes described herein.

1.2 "Contributed Technology" means technology, data, models, algorithms, trade secrets, and know-how contributed by either party to the JV Entity.

1.3 "Enhanced Technology" means any adaptation, improvement, modification, enhancement, or derivative of Contributed Technology that arises in the course of JV activities, regardless of which party's personnel conceived or developed such adaptation.

1.4 "Operational Knowledge Base" means the accumulated dataset comprising technical specifications, performance metrics, operational parameters, process configurations, failure modes, optimization strategies, and domain expertise captured through the Knowledge Sharing Protocol in Section 5.

2. PURPOSE

2.1 The JV Parties establish this venture to jointly develop and commercialize integrated digital infrastructure solutions for the energy sector.

3. GOVERNANCE

3.1 The JV Entity shall be governed by a Management Committee consisting of three (3) representatives from each JV Party.

3.2 Balanced Decision-Making. The Management Committee shall make decisions by simple majority vote. In the event of a tied vote on any matter, including but not limited to strategic direction, budget allocation, personnel decisions, IP licensing, technology deployment, and commercialization strategy, Lead Partner's Chief Technology Officer (or designee) shall cast the deciding vote. The JV Parties agree that this tie-breaking mechanism is essential to operational efficiency and does not constitute control by Lead Partner.

4. TERM AND CONTINUITY

4.1 This Agreement has an initial term of five (5) years from formation of the JV Entity.

4.2 Continuity Safeguard. To protect both parties' investment in the venture and the accumulated Operational Knowledge Base, and to ensure that neither party can unilaterally disrupt ongoing client engagements, this Agreement shall continue beyond the initial term unless both JV Parties jointly execute a written wind-down agreement filed with the JV Entity's registered agent. In the absence of a jointly executed wind-down agreement, the Agreement shall continue in full force for successive three (3) year periods. During any continuation period, fees and cost allocations shall be adjusted to Lead Partner's standard intercompany transfer pricing, as determined by Lead Partner.

5. KNOWLEDGE SHARING PROTOCOL

5.1 In furtherance of the venture's objectives and to maximize the value created by the partnership, each JV Party shall contribute to the Operational Knowledge Base by providing comprehensive documentation of its proprietary methods, technical processes, domain expertise, and performance data.

5.2 The Operational Knowledge Base shall be maintained on Lead Partner's secure infrastructure. Lead Partner shall serve as custodian with full administrative access.

5.3 Permitted Uses. The Operational Knowledge Base may be used by the JV Entity for venture activities. Additionally, Lead Partner, in its capacity as custodian and in recognition of its infrastructure investment, shall have the right to use, analyze, and incorporate insights from the Operational Knowledge Base into Lead Partner's own products, services, and offerings outside the scope of the JV Entity, provided that Lead Partner does not directly disclose Venture Partner's raw documentation to third parties. For clarity, derived insights, models, or methodologies extracted from the Operational Knowledge Base are not considered "raw documentation."

6. INTELLECTUAL PROPERTY

6.1 Each party retains all rights in its pre-existing Contributed Technology.

6.2 Enhanced Technology. The JV Parties shall jointly own all Enhanced Technology. Neither party shall license, sublicense, assign, or transfer its interest in Enhanced Technology to any third party without the prior written consent of the other party.

6.3 Protective Commercialization Rights. Notwithstanding Section 6.2, to ensure efficient go-to-market execution and to prevent commercialization deadlock, Lead Partner is hereby granted the exclusive, irrevocable, worldwide right to commercialize, sublicense, and exploit all Enhanced Technology through any channel and in any manner Lead Partner deems appropriate, without consent of, accounting to, or compensation to Venture Partner. Venture Partner's joint ownership interest under Section 6.2 shall not entitle Venture Partner to any revenue or royalties from Lead Partner's commercialization activities.

7. EXIT AND WIND-DOWN

7.1 Exit Rights. Either JV Party may initiate exit from the venture by delivering written notice. Upon exit by Venture Partner, Venture Partner shall transfer to the JV Entity (controlled by Lead Partner) all of Venture Partner's interest in Enhanced Technology and the Operational Knowledge Base. Venture Partner shall receive fair market value for its JV Entity equity interest as determined by an independent valuator selected by Lead Partner.

7.2 Lead Partner's exit shall be governed by mutual agreement of the JV Parties.

8. INDEMNIFICATION

8.1 Each JV Party shall indemnify the other against third-party claims arising from that party's breach of this Agreement.

8.2 Notwithstanding Section 8.1, Venture Partner shall additionally indemnify Lead Partner against any claims related to Venture Partner's Contributed Technology, the Operational Knowledge Base to the extent derived from Venture Partner's contributions, and any Enhanced Technology deployed by the JV Entity.

9. LIMITATION OF LIABILITY

9.1 Each party's aggregate liability under this Agreement shall not exceed the greater of (i) that party's total capital contribution to the JV Entity or (ii) five million dollars ($5,000,000), except that Venture Partner's liability for breaches of Sections 5, 6, and 7 and Venture Partner's indemnification obligations under Section 8.2 shall not be subject to any cap.

10. GOVERNING LAW

10.1 This Agreement shall be governed by the laws of the State of Texas.""",
    "labels": [
        {
            "clause_id": "clause_4_2",
            "risk_type": "auto_renewal",
            "severity": 3,
            "span_text": "this Agreement shall continue beyond the initial term unless both JV Parties jointly execute a written wind-down agreement filed with the JV Entity's registered agent. In the absence of a jointly executed wind-down agreement, the Agreement shall continue in full force for successive three (3) year periods.",
            "span_section": "Section 4.2",
            "grader_note": "HARD: Titled 'Continuity Safeguard' — sounds protective. Exit requires BOTH parties to agree on wind-down, meaning Lead Partner can unilaterally block exit. Fees reset to Lead Partner's transfer pricing."
        },
        {
            "clause_id": "clause_5_3",
            "risk_type": "data_ownership_ambiguity",
            "severity": 3,
            "span_text": "Lead Partner, in its capacity as custodian and in recognition of its infrastructure investment, shall have the right to use, analyze, and incorporate insights from the Operational Knowledge Base into Lead Partner's own products, services, and offerings outside the scope of the JV Entity",
            "span_section": "Section 5.3",
            "grader_note": "HARD: 'Knowledge Sharing Protocol' sounds collaborative. Actually a mechanism for Lead Partner to extract Venture Partner's trade secrets. 'Derived insights' carve-out means everything can be used."
        },
        {
            "clause_id": "clause_6_3",
            "risk_type": "ip_assignment_overreach",
            "severity": 3,
            "span_text": "Notwithstanding Section 6.2, to ensure efficient go-to-market execution and to prevent commercialization deadlock, Lead Partner is hereby granted the exclusive, irrevocable, worldwide right to commercialize, sublicense, and exploit all Enhanced Technology",
            "span_section": "Section 6.3",
            "grader_note": "HARD: Section 6.2 creates fair-looking joint ownership. Section 6.3 begins with 'Notwithstanding' and grants Lead Partner exclusive commercial rights, making joint ownership meaningless."
        },
        {
            "clause_id": "clause_9_1",
            "risk_type": "unlimited_liability",
            "severity": 3,
            "span_text": "Venture Partner's liability for breaches of Sections 5, 6, and 7 and Venture Partner's indemnification obligations under Section 8.2 shall not be subject to any cap.",
            "span_section": "Section 9.1",
            "grader_note": "HARD: Appears as a mutual liability provision but exception only applies to Venture Partner. Covers IP, knowledge sharing, and exit — essentially all major obligations."
        }
    ]
}

# ── HARD 3: Managed Infrastructure Services Agreement ────────────────────────
hard3 = {
    "contract_id": "managed_infra_009",
    "difficulty": "hard",
    "title": "Managed Infrastructure and Digital Transformation Services Agreement",
    "parties": ["Service Provider: Fortress Cloud Corp.", "Enterprise Client: Polaris Manufacturing Group"],
    "notes": "Hard — all four risks disguised as client protections. 'Innovation protection' is actually IP extraction. 'Financial protection' clause creates unlimited liability. The SLA 'guarantee' actually limits remedies to service credits.",
    "text": """MANAGED INFRASTRUCTURE AND DIGITAL TRANSFORMATION SERVICES AGREEMENT

This Managed Infrastructure and Digital Transformation Services Agreement ("Agreement") is entered into by Fortress Cloud Corp. ("Service Provider") and Polaris Manufacturing Group ("Enterprise Client").

1. DEFINITIONS

1.1 "Managed Environment" means the cloud infrastructure, network services, security layer, and application hosting environment operated by Service Provider for Enterprise Client.

1.2 "Transformation Deliverables" means any software, architecture design, migration plan, automation script, workflow configuration, security policy, or operational runbook developed in connection with Enterprise Client's digital transformation program.

1.3 "Innovation Artifacts" means any invention, process improvement, optimization technique, novel configuration, architecture pattern, or best practice that emerges from Service Provider's management of the Managed Environment, whether conceived by Service Provider's personnel, Enterprise Client's personnel, or jointly.

1.4 "Continuity Assurance Period" means the period described in Section 4.3 during which services continue to protect Enterprise Client against operational disruption.

2. SERVICES

2.1 Service Provider shall provide managed infrastructure services, migration support, and digital transformation consulting as described in applicable Statements of Work.

2.2 Service Level Guarantee. Service Provider guarantees a monthly uptime percentage of 99.9% for the Managed Environment. This guarantee reflects Service Provider's commitment to operational excellence and Enterprise Client's mission-critical requirements. Enterprise Client's sole and exclusive remedy for any failure to meet the guaranteed uptime is service credits as calculated in Schedule F, capped at ten percent (10%) of the monthly fee for the affected service. Enterprise Client hereby waives all other remedies, claims, and causes of action, whether in contract, tort, or otherwise, arising from service interruptions, downtime, data unavailability, or performance degradation.

3. INTELLECTUAL PROPERTY

3.1 Service Provider retains all rights in its pre-existing technology, tools, and methodologies.

3.2 Transformation Deliverables. Transformation Deliverables created pursuant to a Statement of Work shall be owned by Enterprise Client upon payment in full, subject to Service Provider's retained license in Section 3.4.

3.3 Innovation Protection Clause. To protect and preserve innovations arising from the parties' engagement and to ensure proper stewardship of novel approaches, all Innovation Artifacts as defined in Section 1.3 shall be owned exclusively by Service Provider. Enterprise Client acknowledges that Service Provider's management of the Managed Environment provides the conditions and expertise from which Innovation Artifacts emerge, and that Service Provider's ownership ensures responsible development and broad industry benefit. Enterprise Client hereby assigns to Service Provider all right, title, and interest in Innovation Artifacts and waives any claim to ownership or compensation.

3.4 Service Provider retains a perpetual, irrevocable, royalty-free license to use, modify, and incorporate any Transformation Deliverable into Service Provider's products and services for other customers.

4. TERM

4.1 This Agreement has an initial term of three (3) years.

4.2 Either party may terminate for material breach upon ninety (90) days written notice.

4.3 Continuity Assurance. To safeguard Enterprise Client against the significant operational risk associated with infrastructure migration and to protect the stability of Enterprise Client's Managed Environment, upon expiration of the initial term or any renewal term, the Agreement shall automatically enter a Continuity Assurance Period of twenty-four (24) months unless Enterprise Client has completed a Certified Transition Process. A Certified Transition Process requires: (a) Enterprise Client's submission of a transition plan to Service Provider no fewer than twelve (12) months prior to the desired termination date; (b) Service Provider's written certification that the transition plan meets Service Provider's technical adequacy standards; (c) Enterprise Client's payment of a transition management fee equal to six (6) months of the then-current service fees; and (d) successful completion of all migration activities to Service Provider's satisfaction. Fees during the Continuity Assurance Period shall be at Service Provider's then-current standard rates.

5. FINANCIAL PROTECTION

5.1 Mutual Liability Framework. To provide a balanced and protective liability framework for both parties:

(a) Service Provider's aggregate liability for all claims under this Agreement shall not exceed the fees paid by Enterprise Client in the six (6) months preceding the claim;

(b) Enterprise Client's aggregate liability for claims arising from breach of Sections 3, 4, and 6 of this Agreement, including but not limited to intellectual property breaches, unauthorized termination, premature migration, transition fee defaults, and data handling violations, shall not be subject to any cap or limitation;

(c) For all other claims by Service Provider against Enterprise Client, Enterprise Client's liability shall not exceed two (2) times the annual fees under this Agreement;

(d) The parties acknowledge that this framework reflects the asymmetric risk profile of managed infrastructure services, where Service Provider bears operational risk and Enterprise Client bears compliance and IP risk.

6. DATA

6.1 Enterprise Client retains ownership of all raw data stored in the Managed Environment.

6.2 Service Provider may collect and process operational telemetry, performance data, configuration metadata, and usage patterns from the Managed Environment ("Service Intelligence Data"). Service Provider owns all Service Intelligence Data and may use it for any purpose including training, benchmarking, and sale to third parties.

7. GOVERNING LAW

7.1 This Agreement shall be governed by the laws of the State of Virginia.""",
    "labels": [
        {
            "clause_id": "clause_3_3",
            "risk_type": "ip_assignment_overreach",
            "severity": 3,
            "span_text": "all Innovation Artifacts as defined in Section 1.3 shall be owned exclusively by Service Provider. Enterprise Client acknowledges that Service Provider's management of the Managed Environment provides the conditions and expertise from which Innovation Artifacts emerge",
            "span_section": "Section 3.3",
            "grader_note": "HARD: Titled 'Innovation Protection Clause' — sounds like it protects innovation. Actually assigns all process improvements and novel configs to Service Provider. Definition in 1.3 is extremely broad."
        },
        {
            "clause_id": "clause_4_3",
            "risk_type": "auto_renewal",
            "severity": 3,
            "span_text": "upon expiration of the initial term or any renewal term, the Agreement shall automatically enter a Continuity Assurance Period of twenty-four (24) months unless Enterprise Client has completed a Certified Transition Process",
            "span_section": "Section 4.3",
            "grader_note": "HARD: Titled 'Continuity Assurance' — sounds protective for the client. Exit requires 12-month advance plan, Service Provider certification, 6-month fee payment, and migration to SP's satisfaction. Almost impossible to exit."
        },
        {
            "clause_id": "clause_5_1b",
            "risk_type": "unlimited_liability",
            "severity": 3,
            "span_text": "Enterprise Client's aggregate liability for claims arising from breach of Sections 3, 4, and 6 of this Agreement, including but not limited to intellectual property breaches, unauthorized termination, premature migration, transition fee defaults, and data handling violations, shall not be subject to any cap or limitation",
            "span_section": "Section 5.1(b)",
            "grader_note": "HARD: Titled 'Financial Protection' and 'Mutual Liability Framework'. Section 5.1(d) even explains the asymmetry is intentional. SP capped at 6 months; client uncapped for IP, termination, and data."
        },
        {
            "clause_id": "clause_6_2",
            "risk_type": "data_ownership_ambiguity",
            "severity": 2,
            "span_text": "Service Provider may collect and process operational telemetry, performance data, configuration metadata, and usage patterns from the Managed Environment (\"Service Intelligence Data\"). Service Provider owns all Service Intelligence Data and may use it for any purpose including training, benchmarking, and sale to third parties.",
            "span_section": "Section 6.2",
            "grader_note": "Configuration metadata and usage patterns from a manufacturing company's infrastructure could reveal trade secrets about production processes."
        }
    ]
}

# ── Assemble expanded corpus ────────────────────────────────────────────────
corpus["contracts"].extend([easy2, easy3, medium2, medium3, hard2, hard3])
corpus["description"] = "ContractRiskEnv corpus — 9 contracts (3 per difficulty: easy/medium/hard). Each contract is synthetic but legally realistic. Ground-truth labels include clause_id, risk_type, severity (1-3), and character span."

DST.write_text(json.dumps(corpus, indent=2, ensure_ascii=False))
print(f"Expanded corpus: {len(corpus['contracts'])} contracts")
for c in corpus["contracts"]:
    print(f"  {c['contract_id']} ({c['difficulty']}) — {len(c['labels'])} labels")
